### ISSUE TITLE
Saving images with specified name

### ISSUE THREAD

**Issue by tristan3214** [UWMRO/ScienceCamera#16]
Client receives back the path to the image the server used; the client uses the path to copy the image with the name they have specified.  In the case of a series image a standard format of "_XXX" is appended to the end of the name and iterated if there is such a format available.  This number can go from 001 and up.

May be useful to create a log of names so that if something critically goes wrong then there is a list of names that go with the image names that are simply dated.  A quick script could be used to copy and name all the images appropriately, and in general it would help keep track of all the images accrued by the server.

Need to decide if all this functionality should be done on the client side or server side.  For now, the copying is handled by the client.

**Comment by jwhueh** [comment]
copying should always be handled on client side.  It should always pull.  The server knows nothing about the client architecture and should not really need to.

Joseph Huehnerhoff
jwhueh@gmail.com
425.293.4328

**Comment by ojf** [comment]
Is the plan still to populate an archive (like at apo) as well as save the images locally? Does the user get to chooes which images to save? If so, would we only archive images that the user chooses to save, or archive every image (for example, test exposures)? Many questions, I know--sorry!

**Comment by tristan3214** [comment]
With add_headers floating around I think the GUI will have to run on the new TCC so all the files would be saved twice, one with a time stamp the other with the actual name.  The actual name files would have add_headers write to it.

The way my code currently works is that it sends a message to the server, the server starts the acquisition and will write camera information into the headers; it then sends off the file path to the client.  This process takes around a few microseconds, so once you inject some outside code like add_headers.py into the process that time is greatly increased.  If I were to save to somebody's laptop add_headers wouldn't be able to write to the headers fast enough, I suspect, before the image path is sent off and the client saves that image to their local machine. 

If add_headers was interjected between the time I save the image and send off the image path then there wouldn't be any problem.

As an adhoc I suppose the client could wait to save by checking that image file until it sees add_headers has written to it.

**Comment by ojf** [comment]
Ah--thanks for your super clear explanation. I have good news: add_headers is stand-alone, and doesn't edit files, it just copies ones that are already on the client, and makes a new file in a new location. For 481 we're going to have people use Geezil as the client because the sharing with GTCC that add_headers depends on is already setup. So, unless the Evora software is editing files on the client, we should be just fine.

**Comment by tristan3214** [comment]
In single exposure mode user inputs a name that will be checked against in the directory that was set using the new set save directory button.  If there it will ask if the user would like to clobber the file.

In real time mode, the save name field transitions to read only and is populated with a message of "No name needed".  These images are saved and simply thrown out.

In series mode the user can input an image name and give the number of images in which case "_XXX" will be appended to each image.  It will check to see if a name_001 exists before starting.  If the user wishes to pick up where they left off they simply specify the image name with the number that would be next in the format of _XXX.  Note the Counter does not stop at 999 only that most people can be in the hundreds with images but not in the thousands so for ease of manipulation I only go out 3 digits as a standard.
