### ISSUE TITLE
Incorrect airmass written into FITS header

### ISSUE THREAD

**Issue by Ssoyrnoz** [UWMRO/ScienceCamera#26]
Evora header seems to display an incorrect airmass. Header airmass = sec(Z). Problem seems to stem from an incorrect zenith angle.

**Comment by tristan3214** [comment]
Can confirm it is likely from the logs reporting a wrong zenith angle.  Line 554 of the evora_server.py in the getHeader_2 method is where I compute the airmass for the image headers based on the Z reported by Heimdall (at the time of writing this).  It is a simple computation of 1/cos(Z).  Not much to go wrong there.

**Comment by Ssoyrnoz** [comment]
That sounds about right. I will see if I can track down the cause of the
incorrect zenith angle this weekend. Is there an easy way to access the log
stream from Heimdall to watch what data is being fed to Evora?

On Tue, Jul 10, 2018 at 9:39 AM, Tristan J. Hillis <notifications@github.com

**Comment by tristan3214** [comment]
I would recommend you just call tail -f on the most current Heimdall log file to see a live feed and verify that zenith angle is correct.

My code seems to pull the most recent log from the following directory on Heimdall: "/home/mro/storage/tcc_data/positionlogs/*.txt"

My code will parse the most recent log and read the columns in as ['time','ra', 'dec', 'epoch', 'lst', 'za'].

Hope that helps.

**Comment by Ssoyrnoz** [comment]
That is super helpful, thank you.

-Matt

**Comment by Ssoyrnoz** [comment]
I checked a tail on the log and it appears the issue is coming from Bifrost. The reported ZA is a constant 46.4109 no matter what the actual ZA is. I am looking for the source of this reporting issue now. Doug, any ideas on where in Bifrost I could look for such an issue?

 

-Matt

**Comment by ojf** [comment]
Appears fixed, closing...
