### ISSUE TITLE
Reorganize into package/modules

### ISSUE THREAD

**Issue by sburris0** [UWMRO/ScienceCamera#29]
Structure should look something like this:

```
evora/
    server/
    client/
        gui/
            gui.py
            img/
        transfer/
    common/
        netconsts.py
README.md
LICENSE.md
tests/
docs/
Pipfile
Pipfile.lock
.gitignore
```

So that things are more organized and things like `import evora.common.netconsts` are possible

**Comment by ojf** [comment]
Nice. That looks good, and hopefully after it’s organized I can figure out what’s in include/.

There’ll also be the TelescopePi code in there, will tests apply to all the code, just Evora, or whatever we want?

**Comment by sburris0** [comment]
Yeah, I was just focusing on the Evora part here. I think in `tests/` we could have a `test_evora_client.py`, `test_evora_server.py`, `test_telescope_pi.py`, etc. Whatever needs testing, just organized by file.

**Comment by ojf** [comment]
Sounds good!
