### ISSUE TITLE
Connect, Disconnect, and Shutdown

### ISSUE THREAD

**Issue by tristan3214** [UWMRO/ScienceCamera#3]
GUI should be able to open with everything disabled.  Upon the user hitting the connect button, the GUI will immediately connect to the server over LAN (potentially WAN in the future) "waking up" the GUI for usage.  Disconnection should simply send a disconnect command for the GUI to stop talking to the GUI; this will "deactivate" functionality in the GUI,such as being able to expose.  Shutdown will both disconnect from the server but also shutdown the camera itself.

**Comment by tristan3214** [comment]
Instead of having a separate shut down command I have opted for giving the server this functionality.  This functionality is as follows: when there is only one client upon connection to the server it will start up the camera, and when there is only one client on a disconnect the camera will shut down.  This leaves the GUI with the options of simply connecting and disconnecting.  If there is one client requesting a connection the GUI will wait for the camera to be completely set up to relinquish control to the user.  If there is only one client that disconnects it will simply lock down the GUI control and destroy the connection.  At this point it is all right to close the GUI, or if the user so chooses to reconnect to the camera.

**Comment by jwhueh** [comment]
the only problem I see with this is that the camera could cycle a lot if the network connection is poor, or the user opens and closes the program.

Maybe instead:  gui starts camera and it stays cooled until a gui tells it to stop.  Or maybe a timeout.  If camera is cold for more than 12 hours it checks connections and then warms.  

An idea.

Joseph Huehnerhoff
jwhueh@gmail.com
425.293.4328

**Comment by tristan3214** [comment]
I will keep an eye on this in the future.  I would like to have some automation to at least the initial setup to the camera so that the user doesn't have to think about a startup button, a connect, disconnect, and shutdown.  There are some ways to know if a disconnect was clean or not and I can possibly use these functionalities for the cases of poor connection.
