### ISSUE TITLE
Taking single images

### ISSUE THREAD

**Issue by tristan3214** [UWMRO/ScienceCamera#5]
Add the functionality to take a single exposure that is followed by visual cues within the GUI that it has completed.  Upon taking an image a progress bar will be started based on the input time, and will finish once the server sends the signal the image is complete.  This will need to be a threaded process to prevent blocking in the GUI.  Functionality, like changing temperature and changing the filter wheel may want to be shutdown during the process.  Once the image is complete the image should auto-load into the image window for quality inspection.

**Comment by tristan3214** [comment]
GUI now is able to take a single image with a specified exposure time reliably now.

- When the user hits expose the command is sent to the server and in that time a progress bar is started that will run for approximately the same time.  The progress bar will finish when the client receives, from the server, information on the image.

- On the client side the image is displayed in a pop-up image window outline the basic statistics of the image, e.g. mean.

This does not produce a copied image with a standard FITs header format yet, but can be easily placed in later.

**Comment by jwhueh** [comment]
does the expose button grey out until an image is readout or does it queue?  Either one is ok, the first is a lot easier.

Joseph Huehnerhoff
jwhueh@gmail.com
425.293.4328

**Comment by tristan3214** [comment]
I haven't decided quite yet; currently I have two buttons, expose and stop.  Expose would change to abort which would be used to simply stop the exposure and throw out the image. Stop would stop the exposure but try to read it out.
Tristan

Date: Sun, 24 Apr 2016 19:21:19 -0700

**Comment by jwhueh** [comment]
that works perfectly.  keep it that way.

Joseph Huehnerhoff
jwhueh@gmail.com
425.293.4328
